### PR TITLE
ISS-24: Fix non-persistent write settings

### PR DESCRIPTION
**Pull request by lloydroc**

### CODE REVIEW

**Comment by MartinHN** [comment]
I would love to see that merged, it took me days to figure this bug out.
I think non persistent settings are pretty common use as a safer way to configure the module without "bricking" it via buggy configs (well playing with the serial baud rate seems the only way to '"brick" it).
I reviewed 170 and 433 docs, they both use C2 and not C3 for non persistent

**Comment by lloydroc** [comment]
Tests are passing.

```
$ python3 ebyte-sx1276/test/e32_test.py
........
----------------------------------------------------------------------
Ran 8 tests in 2.549s

OK
```

I did however get a issue the very first time which I am unable to reproduce. I reset the e32, even after it passed.
```
python3 ebyte-sx1276/test/e32_test.py
.F......
======================================================================
FAIL: test_change_settings (__main__.TestE32ControlSocket)
get the settings, change them, change them back to original
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ebyte-sx1276/test/e32_test.py", line 130, in test_change_settings
    self.assertEqual(bytes[1], bytes_orig[1])
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 8 tests in 2.495s

FAILED (failures=1)
```

**Comment by lloydroc** [comment]
@MartinHN I'm sorry for the trouble. Not sure why this PR was never merged ... I just updated the branch and will merge it.

**Comment by MartinHN** [comment]
Awesome thanks!!

Le sam. 4 nov. 2023, 16:42, Lloyd Rochester ***@***.***> a
écrit :

**Pull request merged**
